server:
    username: ""
    directory: "/config/unbound"
    use-syslog: no
    val-log-level: 2
    interface: 0.0.0.0

    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

    do-ip6: no
    so-sndbuf: 0
    prefetch: yes
    prefetch-key: yes

    auto-trust-anchor-file: "/config/unbound/root.key"
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

    local-zone: "health.amneziawg." static
    local-data: "health.amneziawg. IN A 127.0.0.1"

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1#one.one.one.one
    forward-addr: 1.0.0.1#one.one.one.one